version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    links:
       - redis
       - celery
    depends_on:
       - redis
       - celery
    command:
      flask run --host 0.0.0.0

  redis:
    image: "redis:alpine"
    ports:
      - '6379:6379'
    command:
      redis-server

  celery:
    build: .
    links:
      - redis
    depends_on:
      - redis
    command:
      celery -A App.celery worker
